sudo: required
dist: trusty

notifications:
  email: false

services:
  - docker

language: java

jdk:
  - openjdk7

env:
  global:
    - SONATYPE_USERNAME=mattbrownspotify
    - secure: "CTYWMDSX4LOz2TiYBSqC+7klvafj0wvwcbpyL3TJueWmgKzJwysRqSHxw9JR2rfe8ysSxGFFiRO9HEyJ4o6zTF6kIy9tYsPxvSJ8c9wIEdTbUtGMuWlrhKchuMmdDaWt07/0N2llSB4h3fv53UGglSM+5FJu4e5DxvxUmIx/Zn4="
    - secure: "QxRY5YFvWSMAX8204S442fj0P5dVff8GNbSrylb7T0c2F0xDDQ4kItwc5K9y0r2Z1q0ki4+uBVbPChJg4aJ7xkxWpLI3hyLEKJD/0WmsmEmhFYeETyJfsflv4uXNxTYh0yhDU8iVHSWNgypnNQXOjtADGQ3EHngNd2DtX0DXOz0="
  matrix:
    - DOCKER_VERSION=17.03.1~ce
    - DOCKER_VERSION=17.06.2~ce DOCKER_CE=1
    - DOCKER_VERSION=17.09.1~ce DOCKER_CE=1
    - DOCKER_VERSION=17.12.1~ce DOCKER_CE=1 UPLOAD_SONATYPE=1

before_install:
  # check what version of docker is installed beforehand
  - dpkg -l | grep docker
  # install the version of docker in the DOCKER_VERSION env var
  - ./.travis.sh install_docker
  # uncomment to double-check that the version/config is correct
  # - ./.travis.sh dump_docker_config
  - docker version
  - docker info

script: mvn clean -Dsurefire.rerunFailingTestsCount=1 test

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
  # deploy snapshots to Maven central, but only from master branch
  - "[[ $TRAVIS_BRANCH == \"master\" && $UPLOAD_SONATYPE == \"1\" ]] && mvn --settings sonatype-settings.xml -DskipTests -B deploy"

# To troubleshoot a failing build, you can uncomment this block to dump the
# docker logs in case they are needed for troubleshooting failures. We don't do
# this on every single build as the logs are verbose and noisy.
# after_script:
#   - sudo cat /var/log/upstart/docker.log

branches:
  only:
    - master
