sudo: required
dist: trusty

services:
  - docker

language: java

jdk:
  - oraclejdk7

env:
  global:
    - SONATYPE_USERNAME=mattbrownspotify
    - secure: "CTYWMDSX4LOz2TiYBSqC+7klvafj0wvwcbpyL3TJueWmgKzJwysRqSHxw9JR2rfe8ysSxGFFiRO9HEyJ4o6zTF6kIy9tYsPxvSJ8c9wIEdTbUtGMuWlrhKchuMmdDaWt07/0N2llSB4h3fv53UGglSM+5FJu4e5DxvxUmIx/Zn4="
  matrix:
    - DOCKER_VERSION=1.6.0
    - DOCKER_VERSION=1.7.1
    - DOCKER_VERSION=1.8.3
    - DOCKER_VERSION=1.9.1
    - DOCKER_VERSION=1.10.3
    - DOCKER_VERSION=1.11.2
    - DOCKER_VERSION=1.12.1 UPLOAD_SONATYPE=1

before_install:
  # check what version of docker is installed beforehand
  - dpkg -l | grep docker
  # install the version of docker in the DOCKER_VERSION env var
  - ./.travis.sh install_docker
  # double-check that the version/config is correct
  - ./.travis.sh dump_docker_config
  - docker version
  - docker info

script: mvn test

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)
  # deploy snapshots to Maven central, but only from master branch
  - "[[ $TRAVIS_BRANCH == \"master\" && $UPLOAD_SONATYPE == \"1\" ]] && mvn --settings sonatype-settings.xml -DskipTests -B deploy"

# dump the docker logs in case they are needed for troubleshooting failures
after_script:
  - sudo cat /var/log/upstart/docker.log

branches:
  only:
    - master
